import { StyleSheet } from "react-native";
import { Padding, Border, FontFamily, FontSize } from "../GlobalStyles";
import * as React from "react";
import palette from "../utils/color";

export const guidestyles = StyleSheet.create({
  vectorIconPosition: {
    left: 0,
    position: "absolute",
  },
  startpagePosition: {
    width: 360,
    top: 0,
    left: 0,
    position: "absolute",
  },
  textFlexBox: {
    justifyContent: "center",
    position: "absolute",
  },
  textTypo: {
    textAlign: "center",
    fontFamily: FontFamily.poppinsSemibold,
    fontWeight: "600",
  },
  startpageChild: {
    top: 570,
    width: 513,
    height: 395,
  },
  startpageItem: {
    height: 131,
  },
  startpageInner: {
    height: 170,
  },
  vectorIcon: {
    top: 588,
    width: 437,
    height: 403,
  },
  text: {
    top: 278,
    left: 82,
    fontSize: 24,
    color: palette.black,
    display: "flex",
    alignItems: "flex-end",
    width: 196,
    height: 134,
    textAlign: "center",
    fontFamily: FontFamily.poppinsSemibold,
    fontWeight: "600",
  },
  text1: {
    fontSize: FontSize.size_xl,
    color: palette.white,
  },
  wrapper: {
    top: 439,
    left: 102,
    borderRadius: Border.br_11xl,
    backgroundColor: palette.basePrimary,
    shadowColor: "rgba(0, 0, 0, 0.25)",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 10,
    elevation: 10,
    shadowOpacity: 1,
    height: 49,
    paddingHorizontal: 20,
    paddingVertical: Padding.p_3xs,
    alignItems: "center",
    overflow: "hidden",
  },
  startpage: {
    backgroundColor: palette.tutoback,
    flex: 1,
    width: "100%",
    height: 800,
    overflow: "hidden",
  },
  textPosition: {
    top: 0,
    position: "absolute",
  },
  iconPosition: {
    left: 122,
    position: "absolute",
  },
  rectangleLayout: {
    width: 282,
    position: "absolute",
  },
  textboxShadowBox: {
    paddingVertical: Padding.p_9xs,
    paddingHorizontal: Padding.p_3xs,
    shadowOpacity: 1,
    elevation: 15,
    shadowRadius: 15,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowColor: "rgba(0, 0, 0, 0.25)",
    borderTopRightRadius: Border.br_mini,
    borderTopLeftRadius: Border.br_mini,
  },
  pmTypo: {
    fontFamily: FontFamily.poppinsRegular,
    textAlign: "left",
  },
  hiTextClr: {
    color: palette.white,
    fontFamily: FontFamily.poppinsRegular,
  },
  facilityLayout: {
    width: 136,
    height: 180,
    top: 0,
    position: "absolute",
  },
  imageIconPosition: {
    opacity: 0.8,
    left: "-12.5%",
    bottom: "-11.48%",
    top: "-8.89%",
    height: "120.37%",
    maxHeight: "100%",
    maxWidth: "100%",
    position: "absolute",
    overflow: "hidden",
  },
  ellipsePos1: {
    top: 184,
    left: 195,
    width: 185,
    height: 185,
    position: "absolute",
  },
  ellipsePos3: {
    top: 17,
    left: 277,
    width: 248,
    height: 248,
    position: "absolute",
  },
  rectangleView: {
    top: 40,
    borderRadius: Border.br_11xl,
    backgroundColor: palette.green_100,
    height: 23,
    left: 0,
  },
  text: {
    left: 25,
    fontSize: FontSize.size_xl,
    fontWeight: "800",
    fontFamily: FontFamily.poppinsExtrabold,
    textAlign: "center",
    color: palette.black,
  },
  rectangleParent: {
    top: 449,
    left: 161,
    height: 63,
  },
  ellipseParent: {
    alignContent: "center",
  },
  textExample: {
    textAlign: "left",
    fontSize: FontSize.size_mini,
    color: palette.black,
  },
  textbox11: {
    borderBottomRightRadius: Border.br_mini,
    borderBottomLeftRadius: Border.br_8xs,
    backgroundColor: palette.baseLight,
    flexDirection: "row",
    alignItems: "center",
  },
  pm: {
    fontSize: FontSize.size_8xs,
    color: palette.baseDark,
    display: "none",
    marginTop: 1,
    textAlign: "left",
  },
  textbox1: {
    top: 52,
    width: 161,
    height: 43,
    justifyContent: "center",
    left: 0,
    position: "absolute",
  },
  hiText: {
    textAlign: "right",
    fontSize: FontSize.size_mini,
  },
  textbox12: {
    borderBottomRightRadius: Border.br_8xs,
    borderBottomLeftRadius: Border.br_mini,
    backgroundColor: palette.basePrimary,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  textbox2: {
    left: 69,
    width: 193,
    height: 31,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  textbox1Parent: {
    top: 139,
    width: 262,
    height: 95,
    left: 49,
    position: "absolute",
  },
  imageTrayIcon: {
    width: "125%",
    right: "-12.5%",
  },
  facilityImageIcon: {
    height: "100%",
    width: "99.26%",
    top: "0%",
    right: "0%",
    bottom: "0%",
    left: "0.74%",
    maxHeight: "100%",
    maxWidth: "100%",
    position: "absolute",
    overflow: "hidden",
  },
  nameOfFacility: {
    width: "88.24%",
    top: "73.89%",
    left: "5.88%",
    fontSize: FontSize.size_sm,
    display: "flex",
    alignItems: "flex-end",
    textAlign: "left",
    position: "absolute",
  },
  facilityImgBox: {
    left: 0,
  },
  facilityImgBox1: {
    left: 148,
  },
  imageTrayIcon2: {
    width: "102.94%",
    right: "9.56%",
  },
  facilityImgBox2: {
    left: 296,
  },
  imgFrame: {
    top: 257,
    width: 297,
    height: 180,
    left: 49,
    position: "absolute",
  },
  guideview: {
    backgroundColor: palette.tutoback,
    flex: 1,
    width: "100%",
    height: 800,
    overflow: "hidden",
  },
  vectorLayout: {
    height: 395,
    width: 513,
  },
  textPosition: {
    left: 32,
    top: 0,
    position: "absolute",
  },
  textbox1Position: {
    width: 262,
    left: 49,
    position: "absolute",
  },
  textTypo: {
    fontSize: FontSize.size_mini,
    fontFamily: FontFamily.poppinsRegular,
  },
  textboxFlexBox: {
    alignItems: "flex-end",
    height: 31,
    width: 166,
    left: 96,
    justifyContent: "center",
    position: "absolute",
  },
  textboxShadowBox: {
    borderBottomLeftRadius: Border.br_mini,
    borderBottomRightRadius: Border.br_8xs,
    backgroundColor: palette.basePrimary,
    alignItems: "flex-end",
    paddingVertical: Padding.p_9xs,
    paddingHorizontal: Padding.p_3xs,
    shadowOpacity: 1,
    elevation: 15,
    shadowRadius: 15,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowColor: "rgba(0, 0, 0, 0.25)",
    borderTopRightRadius: Border.br_mini,
    borderTopLeftRadius: Border.br_mini,
    justifyContent: "center",
  },
  selectShadowBox: {
    paddingVertical: Padding.p_5xs,
    backgroundColor: palette.white,
    borderRadius: Border.br_3xs,
    paddingHorizontal: Padding.p_3xs,
    flexDirection: "row",
    shadowOpacity: 1,
    elevation: 15,
    shadowRadius: 15,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowColor: "rgba(0, 0, 0, 0.25)",
    position: "absolute",
  },
  ellipsePos2: {
    left: 153,
    width: 99,
    height: 99,
    top: 0,
    position: "absolute",
  },
  ellipsePos4: {
    top: 28,
    left: 122,
    width: 220,
    height: 220,
    position: "absolute",
  },
  rectangleView: {
    top: 40,
    backgroundColor: palette.green_100,
    height: 23,
    borderRadius: Border.br_11xl,
    left: 0,
    width: 282,
    position: "absolute",
  },
  text: {
    fontSize: FontSize.size_xl,
    fontWeight: "800",
    fontFamily: FontFamily.poppinsExtrabold,
    textAlign: "center",
    color: palette.black,
  },
  rectangleParent: {
    top: 148,
    left: 71,
    height: 63,
    width: 282,
    position: "absolute",
  },
  vectorParent: {
    top: 301,
    left: 90,
    width: 513,
    position: "absolute",
  },
  textExample: {
    textAlign: "left",
    fontFamily: FontFamily.poppinsRegular,
    color: palette.black,
  },
  textboxShadowBox1: {
    alignItems: "center",
    paddingVertical: Padding.p_9xs,
    paddingHorizontal: Padding.p_3xs,
    shadowOpacity: 1,
    elevation: 15,
    shadowRadius: 15,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowColor: "rgba(0, 0, 0, 0.25)",
    backgroundColor: palette.baseLight,
    borderBottomLeftRadius: Border.br_8xs,
    borderBottomRightRadius: Border.br_mini,
    borderTopRightRadius: Border.br_mini,
    borderTopLeftRadius: Border.br_mini,
    flexDirection: "row",
  },
  pm: {
    fontSize: FontSize.size_8xs,
    color: palette.baseDark,
    display: "none",
    marginTop: 1,
    textAlign: "left",
    fontFamily: FontFamily.poppinsRegular,
  },
  textbox1: {
    width: 161,
    height: 43,
    justifyContent: "center",
    left: 0,
    top: 0,
    position: "absolute",
  },
  hiText: {
    textAlign: "right",
    color: palette.white,
    fontFamily: FontFamily.poppinsRegular,
  },
  textbox12: {
    backgroundColor: palette.basePrimary,
  },
  textbox2: {
    top: 95,
  },
  selectBox: {
    top: 46,
    paddingVertical: Padding.p_5xs,
    backgroundColor: palette.white,
    borderRadius: Border.br_3xs,
    left: 0,
  },
  textOfChoice1: {
    fontSize: FontSize.size_sm,
    textAlign: "left",
    fontFamily: FontFamily.poppinsRegular,
    color: palette.black,
  },
  selectBox1: {
    top: 47,
    left: 113,
  },
  textbox1Parent: {
    top: 131,
    height: 126,
  },
  textbox15: {
    backgroundColor: palette.basePrimary,
  },
  textbox21: {
    top: 191,
  },
  selectBox2: {
    top: 46,
    paddingVertical: Padding.p_5xs,
    backgroundColor: palette.white,
    borderRadius: Border.br_3xs,
    left: 0,
  },
  selectBox3: {
    top: 95,
    left: 0,
  },
  selectBox4: {
    left: 115,
    top: 46,
    paddingVertical: Padding.p_5xs,
    backgroundColor: palette.white,
    borderRadius: Border.br_3xs,
  },
  selectBox5: {
    top: 144,
    left: 0,
  },
  textbox1Group: {
    top: 271,
    height: 222,
  },
  text1: {
    fontSize: 25,
    fontWeight: "700",
    fontFamily: FontFamily.poppinsBold,
    color: palette.white,
    textAlign: "left",
  },
  wrapper: {
    top: 691,
    paddingHorizontal: 38,
    paddingVertical: Padding.p_3xs,
    backgroundColor: palette.basePrimary,
    flexDirection: "row",
    borderRadius: Border.br_11xl,
    left: 90,
    position: "absolute",
    overflow: "hidden",
  },
});
